src/clima/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='clima'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth.views import logout
from django.contrib import admin

from .views import home_page, about_page, contact_page, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^sobre/$', about_page, name='about'),
    url(r'^contato/$', contact_page, name='contact'),
    url(r'^login/$', login_page),
    url(r'^registro/$', register_page, name='register'),
    url(r'^carrinho/', include("carrinho.urls", namespace='carrinho')),
    url(r'^registro/$', register_page),
    url(r'^produtos/', include("produtos.urls", namespace='produtos')),
    url(r'^pesquisa/', include("pesquisa.urls", namespace='pesquisa')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^avisos/', include("clima.urls", namespace='clima')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/produtos/urls.py
from django.conf.urls import url
from .views import export_produtos

from .views import (
    ProdutoListView,
    ProdutoDetailSlugView)

urlpatterns = [
    url(r'^$', ProdutoListView.as_view(), name='lista'),
    url(r'^(?P<slug>[\w-]+)/$', ProdutoDetailSlugView.as_view(), name='detalhe'),
    url(r'^export_produtos', export_produtos, name='export_produtos'),
]

src/templates/about.html
{% extends "base.html" %}

{% block content %}
{{ premium_content }}
<div class="columns">
    <div class="column is-full">
        <div class="box has-text-centered">
            <img src="http://www.fatecrp.edu.br/wp-content/themes/fatecrp/dist/img/logo.png" />
            <br/>
            <br/> Projeto desenvolvido por alunos da FATEC-RP para
            <br/>a disciplina de Tópicos especiais em informatica.
        </div>
    </div>
</div>

<div class="tile is-ancestor">
    <div class="tile is-vertical is-12">
        <div class="tile">
            <div class="tile is-parent is-vertical">
                <article class="tile is-child notification is-primary">
                    <p class="title">Desenvolvedores:</p>
                    <p class="subtitle">Leonardo Leoni Maglia
                        <br/>Victor Moura Azevedo</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                    <p class="title">Tecnologias</p>
                    <p class="subtitle">
                        <ul>
                            <li>Python 3.6</li>
                            <li>Django 1.11</li>
                            <li>Bulma 0.7.2</li>
                            <li>GitHub</li>
                        </ul>
                    </p>
                </article>
            </div>
        </div>

    </div>

</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PedeRango</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <style>
        .botao-flutuante {
            position: fixed;
            width: 60px;
            height: 60px;
            bottom: 40px;
            right: 40px;
            background-color: #ff3860;
            color: #FFF;
            border-radius: 50px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;
        }

        .btn-carrinho {
            margin-top: 22px;
        }
    </style>
</head>

<body>
    {% if request.user.is_authenticated %}
        
    <section class="hero is-danger is-large">
        <!-- NAVBAR - BEGIN -->
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a href="{% url 'home' %}" class="navbar-item">
                            <span class="icon is-large">
                     <i class="fas fa-utensils"></i>
                     </span>
                        </a>
                        <span class="navbar-burger burger" data-target="navbarMenuHeroB">
                     </span>
                    </div>
                    <div id="navbarMenuHeroB" class="navbar-menu">
                        <div class="navbar-start">
                            <a href="{% url 'clima:clima' %}" class="navbar-item">
                        Avisos
                        </a>
                            <a href="{% url 'produtos:lista' %}" class="navbar-item">
                        Produtos
                        </a>
                            <a href="{% url 'contact' %}" class="navbar-item">
                        Fale Conosco
                        </a>
                            <a href="{% url 'about' %}" class="navbar-item">
                        Sobre
                        </a>
                        </div>

                        <div class="navbar-end">
                            <span class="navbar-item">
                            <span class="tag is-white">Olá {{ user.get_username }}</span>
                            <span class="tag is-black" style="margin-left: 10px;">
                                <a href="/logout"><span>Sair</span>
                            <span class="icon">
                                        <i class="fas is-small fa-sign-out-alt"></i>
                                    </span>
                            </a>
                            </span>
                            </span>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- NAVBAR - END -->
    </section>

    <br/>

    <!-- CONTENT - BEGIN -->
    <div class="container" style="width: 50%">
        {% block content %} {% endblock content %}
    </div>
    <!-- CONTENT - END -->

    {% else %}
    <style type="text/css">
        body {
            background: #ff3860;
        }

        .centerall {
            height: 100vh;
            padding: 0;
            display: flex;
            flex-wrap: nowrap;
            justify-content: center;
            align-items: center;
        }

        .progress::-webkit-progress-value {
            transition: width 0.5s ease;
        }
    </style>
    <div class="container">
        <div class="centerall">
            <div class="box">
                <p>Você será redirecionado...</p>
                <progress id="progress-bar" class="progress is-success is-large" value="0" max="100"></progress>
            </div>
        </div>
    </div>
    <script>
        var progressArr = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

        function fillProgress() {
            progressArr.forEach(function(num, index) {
                setTimeout(function() {
                    $('#progress-bar').val(num);
                }, 300 * index);
            });
        }

        fillProgress();

        function redirect() {
            window.location.href = "/login/";
        }

        setTimeout(redirect, 3000);
    </script>
    {% endif %}
</body>

</html>

src/templates/home_page.html
{% extends "base.html" %}

{% block content %}

<script>
    window.onload = function() {
        window.location.href = "avisos";
    }
</script>

<div class="columns">
    <div class="column is-full">
        <form>
            <div class="box">
                {{ premium_content }}
                <br/> Lista de pedidos realizados
            </div>
        </form>
    </div>

{% endblock %}