src/carrinho/urls.py
from django.conf.urls import url

from .views import (
    carrinho_home,
    carrinho_update,
    checkout_home,
)

urlpatterns = [
    url(r'^$', carrinho_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', carrinho_update, name='update'),
]

src/clima/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='clima'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth.views import logout
from django.contrib import admin

from .views import home_page, about_page, contact_page, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^sobre/$', about_page, name='about'),
    url(r'^contato/$', contact_page, name='contact'),
    url(r'^login/$', login_page),
    url(r'^registro/$', register_page, name='register'),
    url(r'^carrinho/', include("carrinho.urls", namespace='carrinho')),
    url(r'^registro/$', register_page),
    url(r'^produtos/', include("produtos.urls", namespace='produtos')),
    url(r'^pesquisa/', include("pesquisa.urls", namespace='pesquisa')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^avisos/', include("clima.urls", namespace='clima')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carrinho/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from produtos.models import Produto

User = settings.AUTH_USER_MODEL


class CarrinhoManager(models.Manager):
    def new_or_get(self, request):
        carrinho_id = request.session.get("carrinho_id", None)
        qs = self.get_queryset().filter(id=carrinho_id)
        if qs.count() == 1:
            new_obj = False
            carrinho_obj = qs.first()
            if request.user.is_authenticated() and carrinho_obj.usuario is None:
                carrinho_obj.usuario = request.user
                carrinho_obj.save()
        else:
            carrinho_obj = Carrinho.objects.new(usuario=request.user)
            new_obj = True
            request.session['carrinho_id'] = carrinho_obj.id
        return carrinho_obj, new_obj

    def new(self, usuario=None):
        usuario_obj = None
        if usuario is not None:
            if usuario.is_authenticated():
                usuario_obj = usuario
        return self.model.objects.create(usuario=usuario_obj)  # associando o user logado ao carrinho


class Carrinho(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True)
    produtos = models.ManyToManyField(Produto, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
    updated = models.DateField(auto_now=True)
    timestamp = models.DateField(auto_now_add=True)

    objects = CarrinhoManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_carrinho_receiver(sender, instance, action, *args, **kwargs): # quando a venda é salva, chamamos este método
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        produtos = instance.produtos.all()
        total = 0
        for item in produtos:
            total += item.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_carrinho_receiver, sender=Carrinho.produtos.through)


def pre_save_carrinho_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal +10
    else:
        instance.total = 0.00


pre_save.connect(pre_save_carrinho_receiver, sender=Carrinho)

src/carrinho/views.py
from django.shortcuts import render, redirect

from produtos.models import Produto
from pedidos.models import Pedido
from .models import Carrinho


def carrinho_home(request):
    carrinho_obj, new_obj = Carrinho.objects.new_or_get(request)
    return render(request, "carrinho/home.html", {"carrinho": carrinho_obj})


def carrinho_update(request):
    produto_id = request.POST.get('produtos_id')
    if produto_id is not None:
        try:
            produto_obj = Produto.objects.get(id=produto_id)
        except Produto.DoesNotExist:
            return redirect("carrinho:home")
        carrinho_obj, new_obj = Carrinho.objects.new_or_get(request)
        if produto_obj in carrinho_obj.produtos.all():
            carrinho_obj.produtos.remove(produto_obj)
        else:
            carrinho_obj.produtos.add(produto_obj)
        request.session['total_itens'] = carrinho_obj.produtos.count()
    return redirect("carrinho:home")


def checkout_home(request):
    carrinho_obj, carrinho_criado = Carrinho.objects.new_or_get(request)
    pedidos_obj = None

    if carrinho_criado or carrinho_obj.produtos.count() == 0:
        return redirect("carrinho:home")
    else:
        pedidos_obj, novo_pedido = Pedido.objects.get_or_create(carrinho=carrinho_obj)
    return render(request, "carrinho/checkout.html", {"object": pedidos_obj})

src/carrinho/templates/carrinho/checkout.html
{% extends "base.html" %}

{% block content %}

<article class="message is-dark">
    <div class="message-header">
        <p>Checkout</p>
    </div>
    <div class="message-body">
        <div class="tile is-ancestor">
            <div class="tile is-vertical">
                <div class="tile">
                    <div class="tile is-parent is-vertical">
                        <article class="tile is-child notification is-warning">
                            <p>Total carrinho:</p>
                            <p class="subtitle">R$ {{ object.carrinho.total }}</p>
                        </article>
                    </div>
                    <div class="tile is-parent">
                        <article class="tile is-child notification is-link">
                            <p>Valor entrega:</p>
                            <p class="subtitle">R$ {{ object.valor_entrega }}</p>
                        </article>
                    </div>
                    <div class="tile is-parent">
                        <article class="tile is-child notification is-success">
                            <p>Total pedido:</p>
                            <p class="subtitle">R$ {{ object.total }}</p>
                        </article>
                    </div>
                </div>
            </div>
        </div>

        <br/>
        <div style="text-align:center">
            <a class="button is-dark">Finalizar</a>
        </div>
    </div>
</article>

{% endblock %}

src/carrinho/templates/carrinho/home.html
{% extends "base.html" %}

<!-- CONTENT - BEGIN -->
{% block content %}
<div class="box">
    {% if carrinho.produtos.exists %}
    <table class="table" style="width: 100%">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome do Produto</th>
                <th>Preço</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for produto in carrinho.produtos.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ produto.get_absolute_url }}">{{ produto.name }}</a></td>
                <td>R$ {{ produto.price }}</td>
                <td>{% include 'produtos/snippets/atualizar-carrinho.html' with produto=produto carrinho=carrinho no_carrinho=True %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    {% else %}
    <p class="lead">Carrinho vazio!</p>
    {% endif %}
</div>

{% if carrinho.produtos.exists %}
    <div class="tile is-ancestor">
        <div class="tile is-vertical is-7">
            <div class="tile">
                <div class="tile is-parent is-vertical">
                    <article class="tile is-child notification is-warning">
                        <p>Sub-total:</p>
                        <p class="subtitle">R$ {{ carrinho.subtotal }}</p>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child notification is-link">
                        <p>Total</p>
                        <p class="subtitle">R$ {{ carrinho.total }}</p>
                    </article>
                </div>
            </div>
        </div>

        <a href="{% url "carrinho:checkout" %}" class="button is-success" style="margin-left:120px;margin-top: 35px">Finalizar pedido</a>

    </div>

{% endif %}

{% endblock %}

<a href="{% url 'carrinho:home' %}" class="botao-flutuante">
    <i class="fa fa-shopping-cart btn-carrinho"></i> {{ request.session.total_itens }}
</a>