src/clima/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='clima'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth.views import logout
from django.contrib import admin

from .views import home_page, about_page, contact_page, login_page, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^sobre/$', about_page, name='about'),
    url(r'^contato/$', contact_page, name='contact'),
    url(r'^login/$', login_page),
    url(r'^registro/$', register_page, name='register'),
    url(r'^carrinho/', include("carrinho.urls", namespace='carrinho')),
    url(r'^registro/$', register_page),
    url(r'^produtos/', include("produtos.urls", namespace='produtos')),
    url(r'^pesquisa/', include("pesquisa.urls", namespace='pesquisa')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^avisos/', include("clima.urls", namespace='clima')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pesquisa/urls.py
from django.conf.urls import url

from .views import (
    PesquisaProdutoView,
)

urlpatterns = [
    url(r'^$', PesquisaProdutoView.as_view(), name='query'),
]

src/produtos/urls.py
from django.conf.urls import url
from .views import export_produtos

from .views import (
    ProdutoListView,
    ProdutoDetailSlugView)

urlpatterns = [
    url(r'^$', ProdutoListView.as_view(), name='lista'),
    url(r'^(?P<slug>[\w-]+)/$', ProdutoDetailSlugView.as_view(), name='detalhe'),
    url(r'^export_produtos', export_produtos, name='export_produtos'),
]

src/produtos/models.py
#  classe usada para mapear o banco de dados ORM, no caso está sendo utilizado o sqlite, integrado ao django
#  versão do Django 1.11
import random
import os
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save
from ecommerce.utils import unique_slug_generator


def get_filename_extension(filename):  # usado para pegar a extensão da img que foi upada
    base_name = os.path.basename(filename)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):  # usado para modificar o path da img a ser upada
    new_filename = random.randint(1, 3910230292)
    name, ext = get_filename_extension(filename)
    final_filename = f'{new_filename}{ext}'
    return f"produtos/{new_filename}/{final_filename}"


class ProdutoQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)


class ProdutoManager(models.Manager):
    def get_queryset(self):
        return ProdutoQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None


class Produto(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)  # usado para passar o nome do produto na url
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=10, default=19.99)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    objects = ProdutoManager()

    def get_absolute_url(self):
        # return "/produtos/{slug}/".format(slug=self.slug)
        return reverse("produtos:detalhe", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


# antes do produto ser salvo, é feito o slug no produto a ser inserido

def produto_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(produto_pre_save_receiver, sender=Produto)

src/produtos/views.py
import json
import io

from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from decimal import Decimal

from carrinho.models import Carrinho
from .models import Produto


class ProdutoFeaturedListView(ListView):
    template_name = "produtos/lista.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Produto.objects.all().featured()


class ProdutoFeaturedDetailView(DetailView):
    queryset = Produto.objects.all().featured()
    template_name = "produtos/featured-detail.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Produto.objects.featured()


class ProdutoListView(ListView):
    template_name = "produtos/lista.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProdutoListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Produto.objects.all()


def produto_list_view(request):
    queryset = Produto.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "produtos/lista.html", context)


class ProdutoDetailSlugView(DetailView):
    queryset = Produto.objects.all()
    template_name = "produtos/detalhe.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProdutoDetailSlugView, self).get_context_data(*args, **kwargs)
        carrinho_obj, new_obj = Carrinho.objects.new_or_get(self.request)
        context['carrinho'] = carrinho_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        # instance = get_object_or_404(Produto, slug=slug, active=True)
        # aqui estamos definindo caso retorne multiplos objetos, pegamos o primeiro
        try:
            instance = Produto.objects.get(slug=slug, active=True)
        except Produto.DoesNotExist:
            raise Http404("Produto não encontado!")
        except Produto.MultipleObjectsReturned:
            qs = Produto.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Teste do Joselito")
        return instance


class ProdutoDetailView(DetailView):
    # queryset = Produto.objects.all()
    template_name = "produtos/detalhe.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProdutoDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Produto.objects.get_by_id(pk)
        if instance is None:
            raise Http404("O produto não existe!")
        return instance


def produto_detail_view(request, pk=None, *args, **kwargs):
    # # instance = Produto.objects.get(pk=pk)
    # # instance = get_object_or_404(Produto, pk=pk)
    # try:
    #     instance = Produto.objects.get(id=pk)
    # except Produto.DoesNotExist:
    #     print("Produto não encontrado!")
    #     raise Http404("O produto não existe!")
    # except:
    #     print("q?")
    instance = Produto.objects.get_by_id(pk)
    if instance is None:
        raise Http404("O produto não existe!")
    # print(instance)
    # qs = Produto.objects.filter(id=pk)
    # if qs.exists() and qs.count() == 1:
    #     instance = qs.first()
    # else:
    #     raise Http404("O produto não existe!")

    context = {
        'object': instance
    }
    return render(request, "produtos/detalhe.html", context)


def _json_encoder(obj):
    if isinstance(obj, Decimal):
        return float(obj)

def export_produtos(request):
    data = list(Produto.objects.values())
    content = io.StringIO()
    json.dump(data, content, default=_json_encoder, indent=4, sort_keys=True, ensure_ascii=False)

    response = HttpResponse(content.getvalue().encode('utf8'), content_type='application/json')
    response['Content-Disposition'] = 'attachment; filename=Produtos.json'

    return response

src/produtos/templates/produtos/detalhe.html
{% extends "base.html" %} {% block content %} {{ premium_content }}

<article class="message is-danger">
    <div class="message-header">
        <p>{{ object.name }}</p>
    </div>
    <div class="message-body">
        <div class="columns">
            <div class="column is-two-fifths">
                <div class="box has-text-centered">
                    {% if object.image %}
                    <img src='{{ object.image.url }}' class="img-fluid" style="width: 200px;height: 200px" /> {% endif %}
                    <br/>
                    <span class="tag is-success is-large">
            R$ {{ object.price }}
          </span>
                </div>
            </div>
            <div class="column">
                {{ object.description }}

                <br/>
                <br/> {% include 'produtos/snippets/atualizar-carrinho.html' with produto=object carrinho=carrinho %}
            </div>
        </div>

        <div style="clear: both;"></div>
    </div>
</article>

{% if user.is_superuser %}
<div style="float: right;">
    <a class="button is-small is-warning" href="http://127.0.0.1:8000/admin/produtos/produto/{{ object.id }}/change/">
        <span class="icon">
              <i class="fas is-small fa-edit"></i>
          </span>
        <span>Editar</span>
    </a>

    <a class="button is-small is-danger" href="http://127.0.0.1:8000/admin/produtos/produto/{{ object.id }}/delete/">
        <span class="icon">
              <i class="fas is-small fa-trash"></i>
          </span>
        <span>Excluir</span>
    </a>
</div>
{% endif %}

<a href="{% url 'carrinho:home' %}" class="botao-flutuante">
    <i class="fa fa-shopping-cart btn-carrinho"></i> {{ request.session.total_itens }}
</a>
{% endblock %}

src/produtos/templates/produtos/featured-detail.html
{{ object.name }} <br/>
{{ object.description }} <br/>
{% if object.image %}
    <img src='{{ object.image.url }}' class="img-fluid" style="width: 200px;height: 200px" />
{% endif %}

src/produtos/templates/produtos/lista.html
{% extends "base.html" %}

{% block content %}

    {% if user.is_superuser %}
    <div style="float: right;">
        <a class="button is-link is-small" href="http://127.0.0.1:8000/admin/produtos/produto/add/">
            <span class="icon is-small">
                      <i class="fas fa-plus"></i>
                  </span>
            <span>Novo produto</span>
        </a>

        <a class="button is-success is-small" href="{% url 'produtos:export_produtos' %}">
            <span class="icon is-small">
                      <i class="fas fa-file-export"></i>
                  </span>
            <span>Exportar</span>
        </a>
    </div>
    {% endif %}

    <form method="GET" action="{% url "pesquisa:query" %}">
        <div class="field has-addons">
            <div class="control">
                <input class="input" type="text" placeholder="Buscar produto" name="q">
            </div>
            <div class="control">
                <button type="submit" class="button is-danger">
                    Buscar
                </button>
            </div>
        </div>
    </form>

    {{ premium_content }}

    <div class="columns" style="margin-top: 10px">
        {% for obj in object_list %}
        <div class="column is-one-third">
            {% include 'produtos/snippets/card.html' with instance=obj %}
        </div>
        {% endfor %}
    </div>

    <a href="{% url 'carrinho:home' %}" class="botao-flutuante">
        <i class="fa fa-shopping-cart btn-carrinho"></i> {{ request.session.total_itens }}
    </a>

{% endblock %}